### ISSUE TITLE
`refresh_token` fails when behind a proxy due to incorrect `__refresh_url`

### ISSUE THREAD

**Issue by casparvl** [IKNL/vantage6-client#47]
**Issue**

My Vantage6 node wouldn't start, because it would fail with the following log & backtrace:

```
2022-05-13 09:27:49 - node           - DEBUG    - Creating websocket connection with the server
2022-05-13 09:27:49 - node           - INFO     - connected to host=https://<myhost> on port=443
2022-05-13 09:27:49 - docker.utils.config - DEBUG    - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2022-05-13 09:27:49 - docker.utils.config - DEBUG    - No config file found
2022-05-13 09:27:49 - docker.utils.config - DEBUG    - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2022-05-13 09:27:49 - docker.utils.config - DEBUG    - No config file found
2022-05-13 09:27:49 - network_man..  - DEBUG    - Creating isolated docker-network vantage6-v6surfnode1-user-net!
2022-05-13 09:27:49 - network_man..  - DEBUG    - Network vantage6-v6surfnode1-user-net already exists. Deleting it.
2022-05-13 09:27:49 - node           - DEBUG    - Setting up VPN client container
2022-05-13 09:27:49 - docker.utils.config - DEBUG    - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2022-05-13 09:27:49 - docker.utils.config - DEBUG    - No config file found
2022-05-13 09:27:49 - docker.utils.config - DEBUG    - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2022-05-13 09:27:49 - docker.utils.config - DEBUG    - No config file found
2022-05-13 09:27:49 - node           - DEBUG    - Requesting new VPN configuration file...
2022-05-13 09:27:49 - client         - DEBUG    - Making request: GET | https://<myhost>:443/vantage6/api/vpn | None
2022-05-13 09:27:49 - client         - ERROR    - Server responded with error code: 501
2022-05-13 09:27:49 - client         - ERROR    - msg:This server does not support VPN
2022-05-13 09:27:49 - client         - INFO     - Refreshing token
2022-05-13 09:27:49 - client         - CRITICAL - Could not refresh token
2022-05-13 09:27:49 - node           - INFO     - Disconnected from the server
Traceback (most recent call last):
  File "/usr/local/bin/vnode-local", line 33, in <module>
    sys.exit(load_entry_point('vantage6-node', 'console_scripts', 'vnode-local')())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/vantage6/vantage6-node/vantage6/node/cli/node.py", line 191, in cli_node_start
    node.run(ctx)
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 749, in run
    node = Node(ctx)
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 141, in __init__
    self.initialize()
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 190, in initialize
    isolated_network_mgr, self.ctx)
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 574, in setup_vpn_connection
    ovpn_file)
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 609, in _connect_vpn
    do_try = self._get_vpn_config_file(ovpn_file)
  File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 638, in _get_vpn_config_file
    success, ovpn_config = self.server_io.get_vpn_config()
  File "/vantage6/vantage6-node/vantage6/node/server_io.py", line 322, in get_vpn_config
    response = self.request("vpn")
  File "/vantage6/vantage6-client/vantage6/client/__init__.py", line 209, in request
    self.refresh_token()
  File "/vantage6/vantage6-client/vantage6/client/__init__.py", line 345, in refresh_token
    raise Exception("Authentication Error!")
Exception: Authentication Error!
```

**Minimal reproducer**
```
>>> from vantage6.client import Client
>>> import config
>>>
>>> config.server_api
'/vantage6/api'
>>>
>>> client = Client(config.server_url, config.server_port, config.server_api)
>>> client.authenticate(config.username, config.password)
>>> client.setup_encryption(config.organization_key)
>>> client.refresh_token()
Failed to refresh token at:
self.__host: https://<myserver>, self.__port: 443, self.__refresh_url: /api/token/refresh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cvanleeuwe/.local/lib/python3.8/site-packages/vantage6/client/__init__.py", line 347, in refresh_token
    print(f'self.__host: {self.__host}, self.__port: {self.__port}, self.__refresh_url: {self.__refresh_url}')
Exception: Authentication Error!
```

**Context**
I've set up my Vantage6 server behind a remote proxy. That nginx proxy has a config that looks like this:

```
server {

    # public port
    listen 443 ssl;
    server_name vantage6-server;

    # SSL stuff
    ssl_certificate <somecert>
    ssl_certificate_key <somecert>
    include <some ssl config>
    ssl_dhparam <some ssh stuff>

    # vantage6-server
    location /vantage6/ {
        include proxy_params;

        # internal ip and port
        proxy_pass http://127.0.0.1:5000/;
    }

    # allow the websocket traffic
    location /socket.io/ {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://127.0.0.1:5000/socket.io/;
    }
}
```

In other words the API is running at `https://<myserver>:443/vantage6/api`. Thus, I configured my V6 node with:

```
 cat .config/vantage6/node/v6node1.yaml | grep api_path
  api_path: /vantage6/api
```

**Root cause**

The issue is caused by [this line](https://github.com/IKNL/vantage6-client/blob/95bba9d54e6814f27b78466a31c46828bbf78dcf/vantage6/client/__init__.py#L320), which sets the `self.__refresh_url` as whatever is returned by the server. The Vantage6 server itself thinks it's API is running at `/api` and will return that, but since it is behind a reverse proxy, the API is available at `/vantage6/api` to the outside world.

**Solution**

Well, this is where it gets tricky. Is it a vantage6 bug? Or should the reverse proxy somehow adapt the `refresh_url` that is returned? I'm no expert on reverse proxies, but I think since this is _inside_ a json payload, a reverse proxy would normally not be able to do that. Thus, I think it needs to be solved at the vantage6 side. 

Now, I don't know why the V6 client relies on the `refresh_url` to be returned by the V6 server to begin with: maybe there was a good reason for that. If there was no particular reason for that: the client _could_ just construct the `refresh_url` itself as `self.__refresh_url = f"{self.__api_path}/token/refresh"` . Alternatively, if you don't want to hardcode the `/token/refresh', you could have the server return this part of the API endpoint (i.e. _just_ `/token/refresh`) as `refresh_url` (at least I assume this payload is sent by the V6 server, I haven't found that part of the code tbh) and then construct the full URL as

`url f"{self.__host}:{self.__port}{self.__api_path}{self.__refresh_url}"`

(equivalent to [this line](https://github.com/IKNL/vantage6-client/blob/95bba9d54e6814f27b78466a31c46828bbf78dcf/vantage6/client/__init__.py#L338))

Please let me know what you think about these solutions. If needed, I could make a PR, though the change is probably so small it might be quicker to do it yourself (also, if we go for the second approach, I would need a pointer to where this payload gets constructed by the V6 server).

**Comment by casparvl** [comment]
Just a small note: for my minimal reproducer, I created this hardcoded change, just to demonstrate that this was the issue:

```
def refresh_token(self) -> None:
...
        # hardcode refresh_url for testing:
        self.__refresh_url = '/vantage6/api/token/refresh'

        if self.__port:
            url = f"{self.__host}:{self.__port}{self.__refresh_url}"
        else:
            url = f"{self.__host}{self.__refresh_url}"
...
```

Then, a call to `client.refresh_token()` indeed completes correctly

**Comment by casparvl** [comment]
Hm, another option is to also change the API endpoint on the server config, which might make more sense. In that case, the `nginx` config should e.g. be:

```
    location /vantage6/ {
        include proxy_params;

        # internal ip and port
        proxy_pass http://127.0.0.1:5000/vantage6/;
    }
```
I.e. where the proxy_pass also forwards to `/vantage6`, and then in the server config yaml, we also configure
```
    api_path: /vantage6/api
```
This works, but does mean you are restricted to use have the nginx 'location' and the proxy_pass to point to the same 'suffix' (in this example `/vantage6/`). I can't really oversee if that ever present issues, but at least with this, my setup works without any code changes to the current V6 releases. If you feel that this is the appropriate solution (rather than changing the V6 code), feel free to close this issue.

**Comment by frankcorneliusmartin** [comment]
Thank you for your extensive research into this issue. We had a little discussion internally and think that your last suggestion suits best. This way the endpoints that are returned by the server are correct and do not any modification on the client side in order to work (All endpoints return HATEOS schema's). 

Thus;

* In the server configuration set the `api_path` to include the subpath (in your case `api_path: /vantage6/api`)
* In NGINX Forward the _location_ in the `proxy_pass` directive

No code changes are required, but we will update the documentation to avoid the confusion in the future.

**Comment by frankcorneliusmartin** [comment]
Added documentation:
* Added comment to the `api_path` server parameter, [here](https://docs.vantage6.ai/usage/running-the-server/server-configuration#configuration-file-structure)
* Added subpath example to the NGINX example configuration, [here](https://docs.vantage6.ai/usage/running-the-server/deployment#nginx)

I close this issue for now. Feel free to re-open it.
